
CREATE TABLE GYM_CUSTOMER
(
	C_ID NUMBER NOT NULL,
	SSN NUMBER(11) NOT NULL,
	FN VARCHAR2(25) NOT NULL,
	LN VARCHAR2(25) NOT NULL,
	ADDRESS VARCHAR2(40),
	SEX VARCHAR2(20) NOT NULL, 
	PHONE NUMBER(11),
	BATCH_ID NUMBER,
	FACILITY_ID NUMBER,
	TRAINER_SSN NUMBER(11),
	PRIMARY KEY(C_ID)
);

CREATE TABLE GYM_FACILITIES
(
	FACILITY_ID NUMBER NOT NULL,
	TITLE VARCHAR2(100),
	TYPE VARCHAR2(100),
	AMOUNT NUMBER,
	PRIMARY KEY(FACILITY_ID)
);

CREATE TABLE GYM_FITNESS_BRANCH 
(
	B_ID NUMBER NOT NULL,
	ADDRESS VARCHAR2(40) NOT NULL,
	PHONE NUMBER(11) NOT NULL,
	MANAGER_SSN NUMBER(11),
	PRIMARY KEY(B_ID) 
);

CREATE TABLE GYM_BATCHES 
(
	BATCH_ID NUMBER NOT NULL,
	BATCH_TYPE VARCHAR2(100) NOT NULL,
	START_TIME VARCHAR2(20) NOT NULL,
	END_TIME VARCHAR2(20),
	BRANCH_ID NUMBER NOT NULL,
	PRIMARY KEY(BATCH_ID) 
);


CREATE TABLE GYM_CLERK
(	
	CLERK_SSN NUMBER(11) NOT NULL, 
	WEEKLY_SALARY NUMBER NOT NULL,
	PRIMARY KEY (CLERK_SSN)
);

CREATE TABLE GYM_TRAINER
(	
	TRAINER_SSN NUMBER(11) NOT NULL, 
	HOURLY_SALARY NUMBER NOT NULL,
	PRIMARY KEY (TRAINER_SSN)
);

CREATE TABLE GYM_MANAGERS
(	
	MANAGER_SSN NUMBER(11) NOT NULL, 
	MONTHLY_SALARY NUMBER NOT NULL,
	PRIMARY KEY (MANAGER_SSN)
);


CREATE TABLE GYM_CUSTOMER_REPORT
(	
	R_ID NUMBER NOT NULL, 
	AGE NUMBER(3) NOT NULL,
	WEIGHT NUMBER(3) NOT NULL,
	HEIGHT NUMBER(3) NOT NULL,
	FAT_PERCENTAGE NUMBER(2) NOT NULL,
	MUSCLES NUMBER(2) NOT NULL,
	C_ID NUMBER NOT NULL,
	CLERK_SSN NUMBER(11),
	PRIMARY KEY (R_ID)
);

CREATE TABLE GYM_EQUIPMENT
(	
	E_ID NUMBER NOT NULL, 
	E_TYPE VARCHAR2(100) NOT NULL,
	E_CONDITION VARCHAR2(50),
	MANUFACTURER VARCHAR2(200),
	TITLE VARCHAR2(100) NOT NULL,
	BRANCH_ID NUMBER NOT NULL,
	CLERK_SSN NUMBER(11),
	PRIMARY KEY (E_ID)
);

CREATE TABLE GYM_EMPLOYEE
(	
	SSN NUMBER(11) NOT NULL, 
	NAME VARCHAR2(25) NOT NULL,
	ADDRESS VARCHAR2(40) NOT NULL,
	PHONE NUMBER(11),
	BRANCH_ID NUMBER,
	PRIMARY KEY (SSN)
);


CREATE TABLE GYM_TRAINER_BATCH
(	
	BATCH_ID NUMBER NOT NULL, 
	TRAINER_SSN NUMBER(11) NOT NULL,
	PRIMARY KEY (BATCH_ID, TRAINER_SSN)
);

CREATE TABLE GYM_BRANCH_FACILITIES
(	
	BRANCH_ID NUMBER NOT NULL, 
	FACILITY_ID NUMBER NOT NULL,
	PRIMARY KEY (BRANCH_ID, FACILITY_ID)
);
